eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8888
spring:
  application:
    name: service-shopping
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
feign:
  hystrix:
    enabled: true

mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.jk.model
  mapper-locations: classpath:mapper/*.xml
  property:
    order: BEFORE
    configuration:
      jdbc-type-for-null: null