server:
  port: 8083

spring:
  application:
    name: service-ha
  data:
    solr:
      repositories:
        enabled: true
      zk-host: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
  datasource:
    drivervlassname: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.117:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml


