server:
  port: 8089
spring:
  application:
    name: service-seckill

  datasource:
    drivervlassname: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.117:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.jk.model
  mapper-locations: classpath:mapper/*.xml
  property:
    order: BEFORE
    configuration:
      jdbc-type-for-null: null



